//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAjaxClient.WCFAjaxService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFAjaxService.IWCFAjaxService")]
    public interface IWCFAjaxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAjaxService/GetData", ReplyAction="http://tempuri.org/IWCFAjaxService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAjaxService/GetData", ReplyAction="http://tempuri.org/IWCFAjaxService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAjaxService/GetUser", ReplyAction="http://tempuri.org/IWCFAjaxService/GetUserResponse")]
        string[] GetUser(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAjaxService/GetUser", ReplyAction="http://tempuri.org/IWCFAjaxService/GetUserResponse")]
        System.Threading.Tasks.Task<string[]> GetUserAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFAjaxServiceChannel : WCFAjaxClient.WCFAjaxService.IWCFAjaxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFAjaxServiceClient : System.ServiceModel.ClientBase<WCFAjaxClient.WCFAjaxService.IWCFAjaxService>, WCFAjaxClient.WCFAjaxService.IWCFAjaxService {
        
        public WCFAjaxServiceClient() {
        }
        
        public WCFAjaxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFAjaxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAjaxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAjaxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string[] GetUser(string Id) {
            return base.Channel.GetUser(Id);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUserAsync(string Id) {
            return base.Channel.GetUserAsync(Id);
        }
    }
}
